Refactor mandataris forms by using form extensions
lblod/app-lokaal-mandatenbeheer pull request #188
Opened 2024-08-19 09:13 UTC by bfidlers

## Description

Reused the common logic in mandataris forms and made them extend each other. Mandataris-new now extends mandataris-edit and mandataris-ext extends mandataris-new.
All mandataris forms now have a link-to-besluit form. We probably don't want this, but we need to see how we want to use the link-to-besluit.
Also removed the bestuursorgaan-ext forms, since they where a proof of concept and we now actually extend forms in a useful way.
 
## How to test

Open a mandataris-new, mandataris-edit and mandataris-ext form and see if they still work.

2024-08-21 10:04 UTC, JonasVanHoof requested changes
Fractie selector brakes as it does not find the person in the form.. when creating a new mandataris

2024-08-22 14:00 UTC, JonasVanHoof approved these changes
> Fractie selector brakes as it does not find the person in the form.. when creating a new mandataris

This should be fixed so if PR https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/305 with the corresponding app PR works this can also be merged


Approving in advance ⚠️

2024-08-22 15:05 UTC, JonasVanHoof commented
Sorry for the traffic of comments ;p but can you try and create a new form? It keeps throwing the form is invalid error
![image](https://github.com/user-attachments/assets/19809669-e10d-4a18-9694-74b2e46b3205)

2024-08-23 08:14 UTC, Rahien approved these changes

2024-08-23 08:14 UTC, merged