Lmb 1072 | Use generiek prefix with HTTP in our app
lblod/app-lokaal-mandatenbeheer pull request #289
Opened 2024-11-20 12:40 UTC by JonasVanHoof

## Description

Sometimes a triple has a generiek prefix uri with https, this should always be http except for the ldes data

## How to test

See if the query returns any result
```
PREFIX generiekHttps: <https://data.vlaanderen.be/ns/generiek#>
PREFIX generiek: <http://data.vlaanderen.be/ns/generiek#>

SELECT ?p ?pHttp
WHERE {
  GRAPH ?g {
    ?s ?p ?o.
  }
  FILTER (STRSTARTS(STR(?p), STR(generiekHttps:)))
}
```

2024-11-22 08:15 UTC, JonasVanHoof commented on config/ldes-delta-pusher/handle-membership-type.ts
> +        generiekS:einde ?einde ;
Construct returns

![image](https://github.com/user-attachments/assets/ec1080e6-24eb-46c3-b232-10b8ee1b0388)

2024-11-26 14:27 UTC, Rahien requested changes

2024-11-26 14:27 UTC, Rahien commented on config/migrations/2024/20241120124400-generic-prefix-http.sparql
> +  FILTER (STRSTARTS(STR(?p), STR(generiekHttps:)))
let's not do this and just define all predicates manually

2024-11-26 14:32 UTC, Rahien commented on config/migrations/2024/20241120124400-generic-prefix-http.sparql
> +  FILTER (STRSTARTS(STR(?p), STR(generiekHttps:)))
the reason why:
- this is inefficient
- this way we aren't 100% sure about what we are doing

2024-11-27 10:58 UTC, JonasVanHoof commented on config/migrations/2024/20241120124400-generic-prefix-http.sparql
> +    }
test query 
```sparql

PREFIX generiekHttps: <https://data.vlaanderen.be/ns/generiek#>
PREFIX generiek: <http://data.vlaanderen.be/ns/generiek#>

INSERT DATA {
   GRAPH <http://mu.semte.ch/graphs/public> {
  <http://somehting-one> generiekHttps:begin <http://generiek-https-one>.
  <http://somehting-one> generiekHttps:einde <http://generiek-https-one-einde>.
  <http://somehting-one> generiek:einde <http://generiek-http-one-einde>.

}
}

2024-11-27 11:05 UTC, Rahien approved these changes

2024-11-27 12:03 UTC, merged