allow read access for vendors through authenticated sparql endpoint
lblod/app-lokaal-mandatenbeheer pull request #87
Opened 2024-03-19 14:36 UTC by Rahien

This adds an authenticated sparql endpoint that vendors can use to have read access to all the data visible to an organization.

I've attached a bruno collection that can be used to test this service.

Note that the sparql query i used in bruno uses the plain sparql syntax which isn't supported in the standard mu-auth yet (see https://github.com/mu-semtech/mu-authorization/pull/20/files), you can replace it by a query param with the url encoded sparql query instead.

[vendor sparql.json](https://github.com/lblod/app-lokaal-mandatenbeheer/files/14652060/vendor.sparql.json)

2024-03-25 08:25 UTC, bfidlers commented on config/authorization/config.ex
> +          FILTER( ?session_role = \"LoketLB-vendorManagementGebruiker\" )
We don't have these session roles anymore

2024-03-25 08:31 UTC, bfidlers commented on config/sparql-authorization-wrapper/filter.js
> +    PREFIX dct: <http://purl.org/dc/terms/>
is there a reason why there are so many unused prefixes here?

2024-03-25 16:19 UTC, ruben-bottu requested changes
Check if session roles are still necessary, otherwise looks good

2024-03-26 14:44 UTC, ruben-bottu commented on README.md
> +An example request to the vendor's sparql endpoint could be a POST with Content-Type: application/x-www-form-urlencoded and body `query=SELECT+DISTINCT+?s+?p+?o+WHERE+{+?s+?p+?o+.+}+LIMIT+10`.
Maybe specify that the query is URI encoded?

2024-03-26 14:59 UTC, ruben-bottu approved these changes
Left some small comments on the README

2024-03-27 07:33 UTC, Rahien commented on README.md
> +New publishers can be registered using a migration e.g. like [this one](./config/migrations/2024/20240319110700-add-vendor-login.sparql). This migration links the vendor's user to the organizations i
not sure if we should care about screen readers in our readme files but i'll change it

2024-03-27 07:36 UTC, merged